apiVersion: v1
kind: Service
metadata:
  name: dummy-http-server-service
  labels:
    tier: backend
spec:
  selector:
    app: python-flask
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80