kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zoo-role
  namespace: zoo
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zoo-rolebinding
  namespace: zoo
subjects:
- kind: ServiceAccount
  name: zoo-guard
  namespace: zoo
roleRef:
    kind: Role
    name: zoo-role
    apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-reader-binding
subjects:
- kind: ServiceAccount
  name: zoo-guard
  namespace: zoo
roleRef:
  kind: ClusterRole
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io